apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-hello.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask-hello.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-hello.name" . }}
    spec:
      containers:
      - name: flask-hello
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
